import { Geist, Geist_Mono, Istok_Web } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Header";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const istokweb = Istok_Web({
  variable: "--font-istok-web",
  subsets: ["latin"],
  weight:'400'
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-mono antialiased`}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
